export const timings = [
  { name: 'United States', delay: 0 },
  { name: 'Canada', delay: 500 },
  { name: 'Mexico', delay: 400 },
  { name: 'Panama', delay: 500 },
  { name: 'Haiti', delay: 400 },
  { name: 'Jamaica', delay: 500 },
  { name: 'Peru', delay: 400 },
  { name: 'Dominican Rep.', delay: 1000 },
  { name: 'Cuba', delay: 1000 },
  // { name: 'Caribbean', delay: 400 }, // Not available
  { name: 'Greenland', delay: 600 },
  { name: 'El Salvador', delay: 600 },
  //
  { name: 'Puerto Rico', delay: 1200 },
  { name: 'Colombia', delay: 500 },
  { name: 'Venezuela', delay: 600 },
  { name: 'Honduras', delay: 600 },
  { name: 'Guyana', delay: 500 },
  { name: 'Guatemala', delay: 1100 },
  { name: 'Bolivia', delay: 600 },
  { name: 'Argentina', delay: 700 },
  { name: 'Ecuador', delay: 500 },
  { name: 'Chile', delay: 500 },
  { name: 'Brazil', delay: 500 },
  //
  { name: 'Costa Rica', delay: 600 },
  { name: 'Belize', delay: 500 },
  { name: 'Nicaragua', delay: 500 },
  { name: 'Bermuda', delay: 500 },
  { name: 'Bahamas', delay: 400 },
  { name: 'Tobago', delay: 400 },
  { name: 'San Juan', delay: 400 },
  { name: 'Paraguay', delay: 800 },
  { name: 'Uruguay', delay: 500 },
  { name: 'Suriname', delay: 500 },
  { name: 'French Guiana', delay: 800 },
  { name: 'Barbados', delay: 400 },
  { name: 'Guam', delay: 400 },

  // Faster music*
  { name: 'Norway', delay: 3700 },
  { name: 'Sweden', delay: 500 },
  { name: 'Iceland', delay: 500 },
  { name: 'Finland', delay: 400 },
  { name: 'Germany', delay: 400 },
  { name: 'Switzerland', delay: 1400 },
  { name: 'Austria', delay: 500 },
  { name: 'Czechoslovakia', delay: 700 },
  { name: 'Italy', delay: 500 },
  { name: 'Turkey', delay: 400 },
  { name: 'Greece', delay: 500 },
  { name: 'Poland', delay: 800 },
  { name: 'Romania', delay: 600 },
  { name: 'United Kingdom', delay: 500 }, // Scotland
  { name: 'Albania', delay: 400 },
  { name: 'Ireland', delay: 400 },
  { name: 'Russia', delay: 400 },
  { name: 'Oman', delay: 400 },

  // Faster music*
  { name: 'Bulgaria', delay: 600 },
  { name: 'Saudi Arabia', delay: 500 },
  { name: 'Hungary', delay: 800 },
  { name: 'Cyprus', delay: 500 },
  { name: 'Iraq', delay: 400 },
  { name: 'Iran', delay: 500 },
  { name: 'Syria', delay: 800 },
  { name: 'Lebanon', delay: 400 },
  { name: 'Israel', delay: 400 },
  { name: 'Jordan', delay: 500 },

  { name: 'Yemens', delay: 400 }, // ?
  { name: 'Kuwait', delay: 400 },
  { name: 'Bahrain', delay: 400 },
  { name: 'Netherlands', delay: 700 },
  { name: 'Luxembourg', delay: 400 },
  { name: 'Belgium', delay: 400 },
  { name: 'Portugal', delay: 400 },
  { name: 'France', delay: 500 },
  { name: 'United Kingdom', delay: 400 }, // England
  { name: 'Denmark', delay: 400 },
  { name: 'Spain', delay: 400 },

  // Even faster music
  { name: 'India', delay: 3000 },
  { name: 'Pakistan', delay: 400 },
  { name: 'Burma', delay: 400 },
  { name: 'Afghanistan', delay: 500 },
  { name: 'Thailand', delay: 500 },
  { name: 'Nepal', delay: 500 },
  { name: 'Bhutan', delay: 400 },
  { name: 'Kampuchea', delay: 500 },
  { name: 'Malaysia', delay: 400 },
  { name: 'Bangladesh', delay: 500 },
  { name: 'Asia', delay: 100 }, // ?
  { name: 'China', delay: 400 },
  { name: 'South Korea', delay: 600 }, // What about North Korea
  { name: 'Japan', delay: 500 },

  /* Even faster music */
  { name: 'Mongolia', delay: 800 },
  { name: 'Laos', delay: 400 },
  { name: 'Tibet', delay: 400 },
  { name: 'Indonesia', delay: 400 },
  { name: 'Philippines', delay: 700 },
  { name: 'Taiwan', delay: 700 },
  { name: 'Sri Lanka', delay: 700 },
  { name: 'New Guinea', delay: 400 },
  { name: 'Sumatra', delay: 400 },
  { name: 'New Zealand', delay: 400 },
  { name: 'Borneo', delay: 800 },
  { name: 'Vietnam', delay: 500 },

  { name: 'Tunisia', delay: 800 },
  { name: 'Morocco', delay: 400 },
  { name: 'Uganda', delay: 400 },
  { name: 'Angola', delay: 400 },
  { name: 'Zimbabwe', delay: 400 },
  { name: 'Djibouti', delay: 400 },
  { name: 'Botswana', delay: 400 },
  { name: 'Mozambique', delay: 1200 },
  { name: 'Zambia', delay: 400 },
  { name: 'Swaziland', delay: 400 },
  { name: 'Gambia', delay: 400 },
  { name: 'Guinea', delay: 400 },
  { name: 'Algeria', delay: 400 },
  { name: 'Ghana', delay: 400 },

  // Much faster music
  { name: 'Burundi', delay: 3000 },
  { name: 'Lesotho', delay: 400 },
  { name: 'Malawi', delay: 400 },
  { name: 'Togo', delay: 400 },
  { name: '', delay: 400 }, // The Spanish Sahara is gone
  { name: 'Niger', delay: 2000 },
  { name: 'Nigeria', delay: 400 },
  { name: 'Chad', delay: 400 },
  { name: 'Liberia', delay: 400 },
  { name: 'Egypt', delay: 400 },
  { name: 'Benin', delay: 400 },
  { name: 'Gabon', delay: 400 },
  { name: 'Tanzania', delay: 400 },
  { name: 'Somalia', delay: 400 },
  { name: 'Kenya', delay: 400 },
  { name: 'Mali', delay: 400 },
  { name: 'Sierra Leone', delay: 400 },
  { name: 'Algiers', delay: 400 },
  { name: 'Dahomey', delay: 400 },
  { name: 'Namibia', delay: 400 },
  { name: 'Senegal', delay: 400 },
  { name: 'Libya', delay: 400 },
  { name: 'Cameroon', delay: 400 },
  { name: 'Congo', delay: 400 },
  { name: 'Zaire', delay: 400 },
  { name: 'Ethiopia', delay: 400 },
  { name: 'Guinea-Bissau', delay: 400 },
  { name: 'Madagascar', delay: 400 },
  { name: 'Rwanda', delay: 400 },
  { name: 'Mahore', delay: 400 },
  { name: 'Cayman', delay: 400 },
  { name: 'Hong Kong', delay: 400 },
  { name: 'Abu Dhabi', delay: 400 },
  { name: 'Qatar', delay: 400 },
  { name: 'Yugoslavia', delay: 400 },
  { name: 'Crete', delay: 400 },
  { name: 'Mauritania', delay: 400 },
  { name: 'Transylvania', delay: 400 },
  { name: 'Monaco', delay: 400 },
  { name: 'Liechtenstein', delay: 400 },
  { name: 'Malta', delay: 400 },
  { name: 'Palestine', delay: 400 },
  { name: 'Fiji', delay: 400 },
  { name: 'Australia', delay: 400 },
  { name: 'Sudan', delay: 400 },
];
