/**
 * Type definitions for LayerChart component catalogs
 *
 * These types describe the structure of catalog JSON files generated by
 * the generate-example-catalog script.
 */

/**
 * Information about a specific example for a component
 */
export interface ExampleInfo {
	/** The name of the example (filename without .svelte extension) */
	name: string;
	/** The URL path to view the example */
	path: string;
}

/**
 * Information about where a component is used across all examples
 */
export interface UsageInfo {
	/** The name of the example file using the component */
	example: string;
	/** The component directory where the example is located */
	component: string;
	/** The URL path to view the example */
	path: string;
	/** The line number where the component is used */
	lineNumber: number;
	/** The trimmed line of code containing the component usage */
	line: string;
}

/**
 * Complete catalog for a component showing all examples and usage
 */
export interface ComponentCatalog {
	/** The name of the component */
	component: string;
	/** All examples specifically created for this component */
	examples: ExampleInfo[];
	/** All places where this component is used across all examples */
	usage: UsageInfo[];
	/** ISO timestamp when the catalog was last updated */
	updatedAt: string;
}
