/**
 * Bundle analysis scenarios representing real-world use cases.
 *
 * Each scenario defines a set of imports that a user would typically
 * use together, letting us track bundle cost for common chart types.
 */

export interface Scenario {
  /** Scenario name shown in reports */
  name: string;
  /** Description of what this scenario represents */
  description: string;
  /** Named imports from "layerchart" */
  imports: string[];
  /** Additional import lines (e.g. from "layerchart/utils/foo") */
  extraImports?: string[];
  /** Optional grouping label used to organize scenarios in the PR comment */
  group?: string;
  /**
   * Per-import sub-path overrides. Maps a component name to a sub-path
   * suffix (e.g. `"svg"` → `"layerchart/svg"`) for scenarios that test
   * per-layer variants of agnostic components.
   *
   * Overrides take precedence over the analyzer's default subpath map.
   */
  layers?: Record<string, string>;
}

export interface ComponentInfo {
  name: string;
}

/**
 * Use-case scenarios that represent how developers actually use layerchart.
 * Each scenario includes the minimum set of components for that chart type.
 */
export const scenarios: Scenario[] = [
  // --- Core ---
  // The bare-bones `<ChartCore>` (no `<ChartChildren>` — no Axis/Grid/Rule/Highlight/Layer).
  // Use cases: geo maps, custom layouts, or anything that doesn't need the cartesian frame.
  {
    name: 'core',
    group: 'Core',
    description: '`ChartCore` — bare-bones chart without `ChartChildren`',
    imports: ['ChartCore'],
  },
  {
    name: 'core-svg',
    group: 'Core',
    description: '`ChartCore` + `Svg` from `layerchart/svg`',
    imports: ['ChartCore', 'Svg'],
    layers: { ChartCore: 'svg', Svg: 'svg' },
  },
  {
    name: 'core-canvas',
    group: 'Core',
    description: '`ChartCore` + `Canvas` from `layerchart/canvas`',
    imports: ['ChartCore', 'Canvas'],
    layers: { ChartCore: 'canvas', Canvas: 'canvas' },
  },
  {
    name: 'core-html',
    group: 'Core',
    description: '`ChartCore` + `Html` from `layerchart/html`',
    imports: ['ChartCore', 'Html'],
    layers: { ChartCore: 'html', Html: 'html' },
  },
  {
    name: 'core-geo',
    group: 'Core',
    description: '`ChartCore`-based geo map (`GeoProjection` + `GeoPath`)',
    imports: ['ChartCore', 'Svg', 'GeoProjection', 'GeoPath'],
  },
  {
    name: 'core-line',
    group: 'Core',
    description: '`ChartCore` + manual `Spline` line (no Axis/Grid)',
    imports: ['ChartCore', 'Svg', 'Spline'],
  },
  {
    name: 'core-scatter',
    group: 'Core',
    description: '`ChartCore` + manual `Points` scatter (no Axis/Grid)',
    imports: ['ChartCore', 'Svg', 'Points'],
  },

  // --- Base (agnostic) ---
  // The full `<Chart>` (with Axis/Grid/Rule/Highlight/Layer/ChartClipPath baked in).
  {
    name: 'base',
    group: 'Base (agnostic)',
    description: '`Chart` — full charting frame without rendering layer',
    imports: ['Chart'],
  },
  {
    name: 'base-svg-agnostic',
    group: 'Base (agnostic)',
    description: '`Chart` + `Svg` from `layerchart` (agnostic dispatcher)',
    imports: ['Chart', 'Svg'],
  },
  {
    name: 'base-canvas-agnostic',
    group: 'Base (agnostic)',
    description: '`Chart` + `Canvas` from `layerchart` (agnostic dispatcher)',
    imports: ['Chart', 'Canvas'],
  },
  {
    name: 'base-html-agnostic',
    group: 'Base (agnostic)',
    description: '`Chart` + `Html` from `layerchart` (agnostic dispatcher)',
    imports: ['Chart', 'Html'],
  },

  // --- Base (layer-specific) ---
  {
    name: 'base-svg',
    group: 'Base (layer-specific)',
    description: '`Chart` + `Svg` from `layerchart/svg`',
    imports: ['Chart', 'Svg'],
    layers: {
      Chart: 'svg',
      Svg: 'svg',
    },
  },
  {
    name: 'base-canvas',
    group: 'Base (layer-specific)',
    description: '`Chart` + `Canvas` from `layerchart/canvas`',
    imports: ['Chart', 'Canvas'],
    layers: {
      Chart: 'canvas',
      Canvas: 'canvas',
    },
  },
  {
    name: 'base-html',
    group: 'Base (layer-specific)',
    description: '`Chart` + `Html` from `layerchart/html`',
    imports: ['Chart', 'Html'],
    layers: {
      Chart: 'html',
      Html: 'html',
    },
  },

  // --- Cartesian charts ---
  {
    name: 'line-chart',
    group: 'Cartesian charts',
    description: 'Basic line chart with axes and grid',
    imports: ['Chart', 'Svg', 'Line', 'Axis', 'Grid'],
  },

  {
    name: 'line-chart-svg',
    group: 'Cartesian charts',
    description: 'Line chart composed from `layerchart/svg`',
    imports: ['Chart', 'Layer', 'Line', 'Axis', 'Grid'],
    layers: {
      Chart: 'svg',
      Layer: 'svg',
      Line: 'svg',
      Axis: 'svg',
      Grid: 'svg',
    },
  },
  {
    name: 'line-chart-canvas',
    group: 'Cartesian charts',
    description: 'Line chart composed from `layerchart/canvas`',
    imports: ['Chart', 'Layer', 'Line', 'Axis', 'Grid'],
    layers: {
      Chart: 'canvas',
      Layer: 'canvas',
      Line: 'canvas',
      Axis: 'canvas',
      Grid: 'canvas',
    },
  },
  {
    name: 'line-chart-html',
    group: 'Cartesian charts',
    description: 'Line chart composed from `layerchart/html`',
    imports: ['Chart', 'Layer', 'Line', 'Axis', 'Grid'],
    layers: {
      Chart: 'html',
      Layer: 'html',
      Line: 'html',
      Axis: 'html',
      Grid: 'html',
    },
  },
  {
    name: 'line-chart-interactive',
    group: 'Cartesian charts',
    description: 'Line chart with tooltip and highlight',
    imports: ['Chart', 'Svg', 'Line', 'Axis', 'Grid', 'Highlight', 'Tooltip'],
  },
  {
    name: 'LineChart',
    group: 'Cartesian charts',
    description: 'High-level `LineChart` component',
    imports: ['LineChart'],
  },
  {
    name: 'LineChart-svg',
    group: 'Cartesian charts',
    description: 'High-level `LineChart` from `layerchart/svg`',
    imports: ['LineChart'],
    layers: { LineChart: 'svg' },
  },
  {
    name: 'LineChart-canvas',
    group: 'Cartesian charts',
    description: 'High-level `LineChart` from `layerchart/canvas`',
    imports: ['LineChart'],
    layers: { LineChart: 'canvas' },
  },
  {
    name: 'area-chart',
    group: 'Cartesian charts',
    description: 'Area chart with axes',
    imports: ['Chart', 'Svg', 'Area', 'Axis', 'Grid'],
  },
  {
    name: 'AreaChart',
    group: 'Cartesian charts',
    description: 'High-level `AreaChart` component',
    imports: ['AreaChart'],
  },
  {
    name: 'AreaChart-svg',
    group: 'Cartesian charts',
    description: 'High-level `AreaChart` from `layerchart/svg`',
    imports: ['AreaChart'],
    layers: { AreaChart: 'svg' },
  },
  {
    name: 'AreaChart-canvas',
    group: 'Cartesian charts',
    description: 'High-level `AreaChart` from `layerchart/canvas`',
    imports: ['AreaChart'],
    layers: { AreaChart: 'canvas' },
  },
  {
    name: 'bar-chart',
    group: 'Cartesian charts',
    description: 'Bar chart with axes',
    imports: ['Chart', 'Svg', 'Bars', 'Axis', 'Grid'],
  },
  {
    name: 'BarChart',
    group: 'Cartesian charts',
    description: 'High-level `BarChart` component',
    imports: ['BarChart'],
  },
  {
    name: 'BarChart-svg',
    group: 'Cartesian charts',
    description: 'High-level `BarChart` from `layerchart/svg`',
    imports: ['BarChart'],
    layers: { BarChart: 'svg' },
  },
  {
    name: 'BarChart-canvas',
    group: 'Cartesian charts',
    description: 'High-level `BarChart` from `layerchart/canvas`',
    imports: ['BarChart'],
    layers: { BarChart: 'canvas' },
  },
  {
    name: 'scatter-chart',
    group: 'Cartesian charts',
    description: 'Scatter plot with points',
    imports: ['Chart', 'Svg', 'Points', 'Point', 'Axis', 'Grid'],
  },
  {
    name: 'ScatterChart',
    group: 'Cartesian charts',
    description: 'High-level `ScatterChart` component',
    imports: ['ScatterChart'],
  },
  {
    name: 'ScatterChart-svg',
    group: 'Cartesian charts',
    description: 'High-level `ScatterChart` from `layerchart/svg`',
    imports: ['ScatterChart'],
    layers: { ScatterChart: 'svg' },
  },
  {
    name: 'ScatterChart-canvas',
    group: 'Cartesian charts',
    description: 'High-level `ScatterChart` from `layerchart/canvas`',
    imports: ['ScatterChart'],
    layers: { ScatterChart: 'canvas' },
  },
  {
    name: 'pie-chart',
    group: 'Cartesian charts',
    description: 'Pie/donut chart with arcs',
    imports: ['Chart', 'Svg', 'Pie', 'Arc', 'ArcLabel'],
  },
  {
    name: 'PieChart',
    group: 'Cartesian charts',
    description: 'High-level `PieChart` component',
    imports: ['PieChart'],
  },
  {
    name: 'PieChart-svg',
    group: 'Cartesian charts',
    description: 'High-level `PieChart` from `layerchart/svg`',
    imports: ['PieChart'],
    layers: { PieChart: 'svg' },
  },
  {
    name: 'PieChart-canvas',
    group: 'Cartesian charts',
    description: 'High-level `PieChart` from `layerchart/canvas`',
    imports: ['PieChart'],
    layers: { PieChart: 'canvas' },
  },
  {
    name: 'ArcChart',
    group: 'Cartesian charts',
    description: 'High-level `ArcChart` component',
    imports: ['ArcChart'],
  },
  {
    name: 'ArcChart-svg',
    group: 'Cartesian charts',
    description: 'High-level `ArcChart` from `layerchart/svg`',
    imports: ['ArcChart'],
    layers: { ArcChart: 'svg' },
  },
  {
    name: 'ArcChart-canvas',
    group: 'Cartesian charts',
    description: 'High-level `ArcChart` from `layerchart/canvas`',
    imports: ['ArcChart'],
    layers: { ArcChart: 'canvas' },
  },

  // --- Geo ---
  {
    name: 'geo',
    group: 'Geo',
    description: 'Geographic map with paths',
    imports: ['Chart', 'Svg', 'GeoProjection', 'GeoPath', 'GeoPoint'],
  },
  {
    name: 'geo-tiles',
    group: 'Geo',
    description: 'Geographic map with tile layer',
    imports: ['Chart', 'Svg', 'GeoProjection', 'GeoPath', 'GeoTile', 'TileImage'],
  },
  {
    name: 'geo-full',
    group: 'Geo',
    description: 'Full geo setup with all geo components',
    imports: [
      'Chart',
      'Svg',
      'GeoProjection',
      'GeoPath',
      'GeoPoint',
      'GeoCircle',
      'GeoSpline',
      'GeoTile',
      'GeoRaster',
      'GeoEdgeFade',
      'GeoVisible',
      'Graticule',
      'GeoLegend',
      'TileImage',
    ],
  },

  // --- Hierarchy ---
  {
    name: 'hierarchy-tree',
    group: 'Hierarchy',
    description: 'Tree layout with links',
    imports: ['Chart', 'Svg', 'Tree', 'Link', 'Circle', 'Text'],
  },
  {
    name: 'hierarchy-treemap',
    group: 'Hierarchy',
    description: 'Treemap layout',
    imports: ['Chart', 'Svg', 'Treemap', 'Group', 'Rect', 'Text'],
  },
  {
    name: 'hierarchy-pack',
    group: 'Hierarchy',
    description: 'Circle packing layout',
    imports: ['Chart', 'Svg', 'Pack', 'Circle', 'Text'],
  },

  // --- Graph / network ---
  {
    name: 'force',
    group: 'Graph / network',
    description: 'Force-directed graph layout',
    imports: ['Chart', 'Svg', 'ForceSimulation', 'Link', 'Circle', 'Text'],
  },
  {
    name: 'dagre',
    group: 'Graph / network',
    description: 'Dagre directed graph layout',
    imports: ['Chart', 'Svg', 'Dagre', 'Link', 'Circle', 'Text'],
  },
  {
    name: 'sankey',
    group: 'Graph / network',
    description: 'Sankey flow diagram',
    imports: ['Chart', 'Svg', 'Sankey', 'Link', 'Rect', 'Text'],
  },
  {
    name: 'chord',
    group: 'Graph / network',
    description: 'Chord diagram',
    imports: ['Chart', 'Svg', 'Chord', 'Ribbon'],
  },

  // --- Components (opt-in per-layer variants) ---
  // Standalone Circle measurements (in isolation — no Chart context, no
  // Highlight pulling in the agnostic version transitively). These are the
  // cleanest way to see what `layerchart/svg` etc. actually save.
  {
    name: 'Circle',
    group: 'Components',
    description: 'Standalone Circle (agnostic) — baseline',
    imports: ['Circle'],
  },
  {
    name: 'Circle.svg',
    group: 'Components',
    description: 'Standalone Circle from `layerchart/svg`',
    imports: ['Circle'],
    layers: { Circle: 'svg' },
  },
  {
    name: 'Circle.canvas',
    group: 'Components',
    description: 'Standalone Circle from `layerchart/canvas`',
    imports: ['Circle'],
    layers: { Circle: 'canvas' },
  },
  {
    name: 'Circle.html',
    group: 'Components',
    description: 'Standalone Circle from `layerchart/html`',
    imports: ['Circle'],
    layers: { Circle: 'html' },
  },
  {
    name: 'Text',
    group: 'Components',
    description: 'Standalone Text (agnostic) — baseline',
    imports: ['Text'],
  },
  {
    name: 'Text.svg',
    group: 'Components',
    description: 'Standalone Text from `layerchart/svg`',
    imports: ['Text'],
    layers: { Text: 'svg' },
  },
  {
    name: 'Text.canvas',
    group: 'Components',
    description: 'Standalone Text from `layerchart/canvas`',
    imports: ['Text'],
    layers: { Text: 'canvas' },
  },
  {
    name: 'Text.html',
    group: 'Components',
    description: 'Standalone Text from `layerchart/html`',
    imports: ['Text'],
    layers: { Text: 'html' },
  },
  {
    name: 'Rect',
    group: 'Components',
    description: 'Standalone Rect (agnostic) — baseline',
    imports: ['Rect'],
  },
  {
    name: 'Rect.svg',
    group: 'Components',
    description: 'Standalone Rect from `layerchart/svg`',
    imports: ['Rect'],
    layers: { Rect: 'svg' },
  },
  {
    name: 'Rect.canvas',
    group: 'Components',
    description: 'Standalone Rect from `layerchart/canvas`',
    imports: ['Rect'],
    layers: { Rect: 'canvas' },
  },
  {
    name: 'Rect.html',
    group: 'Components',
    description: 'Standalone Rect from `layerchart/html`',
    imports: ['Rect'],
    layers: { Rect: 'html' },
  },
  {
    name: 'Line',
    group: 'Components',
    description: 'Standalone Line (agnostic) — baseline',
    imports: ['Line'],
  },
  {
    name: 'Line.svg',
    group: 'Components',
    description: 'Standalone Line from `layerchart/svg`',
    imports: ['Line'],
    layers: { Line: 'svg' },
  },
  {
    name: 'Line.canvas',
    group: 'Components',
    description: 'Standalone Line from `layerchart/canvas`',
    imports: ['Line'],
    layers: { Line: 'canvas' },
  },
  {
    name: 'Line.html',
    group: 'Components',
    description: 'Standalone Line from `layerchart/html`',
    imports: ['Line'],
    layers: { Line: 'html' },
  },
  {
    name: 'Path',
    group: 'Components',
    description: 'Standalone Path (agnostic) — baseline',
    imports: ['Path'],
  },
  {
    name: 'Path.svg',
    group: 'Components',
    description: 'Standalone Path from `layerchart/svg`',
    imports: ['Path'],
    layers: { Path: 'svg' },
  },
  {
    name: 'Path.canvas',
    group: 'Components',
    description: 'Standalone Path from `layerchart/canvas`',
    imports: ['Path'],
    layers: { Path: 'canvas' },
  },
  {
    name: 'ClipPath',
    group: 'Components',
    description: 'Standalone ClipPath (agnostic) — baseline',
    imports: ['ClipPath'],
  },
  {
    name: 'ClipPath.svg',
    group: 'Components',
    description: 'Standalone ClipPath from `layerchart/svg`',
    imports: ['ClipPath'],
    layers: { ClipPath: 'svg' },
  },
  {
    name: 'ClipPath.canvas',
    group: 'Components',
    description: 'Standalone ClipPath from `layerchart/canvas`',
    imports: ['ClipPath'],
    layers: { ClipPath: 'canvas' },
  },
  {
    name: 'ClipPath.html',
    group: 'Components',
    description: 'Standalone ClipPath from `layerchart/html`',
    imports: ['ClipPath'],
    layers: { ClipPath: 'html' },
  },
  {
    name: 'RadialGradient',
    group: 'Components',
    description: 'Standalone RadialGradient (agnostic) — baseline',
    imports: ['RadialGradient'],
  },
  {
    name: 'RadialGradient.svg',
    group: 'Components',
    description: 'Standalone RadialGradient from `layerchart/svg`',
    imports: ['RadialGradient'],
    layers: { RadialGradient: 'svg' },
  },
  {
    name: 'RadialGradient.canvas',
    group: 'Components',
    description: 'Standalone RadialGradient from `layerchart/canvas`',
    imports: ['RadialGradient'],
    layers: { RadialGradient: 'canvas' },
  },
  {
    name: 'LinearGradient',
    group: 'Components',
    description: 'Standalone LinearGradient (agnostic) — baseline',
    imports: ['LinearGradient'],
  },
  {
    name: 'LinearGradient.svg',
    group: 'Components',
    description: 'Standalone LinearGradient from `layerchart/svg`',
    imports: ['LinearGradient'],
    layers: { LinearGradient: 'svg' },
  },
  {
    name: 'LinearGradient.canvas',
    group: 'Components',
    description: 'Standalone LinearGradient from `layerchart/canvas`',
    imports: ['LinearGradient'],
    layers: { LinearGradient: 'canvas' },
  },
  {
    name: 'LinearGradient.html',
    group: 'Components',
    description: 'Standalone LinearGradient from `layerchart/html`',
    imports: ['LinearGradient'],
    layers: { LinearGradient: 'html' },
  },
  {
    name: 'Group',
    group: 'Components',
    description: 'Standalone Group (agnostic) — baseline',
    imports: ['Group'],
  },
  {
    name: 'Group.svg',
    group: 'Components',
    description: 'Standalone Group from `layerchart/svg`',
    imports: ['Group'],
    layers: { Group: 'svg' },
  },
  {
    name: 'Group.canvas',
    group: 'Components',
    description: 'Standalone Group from `layerchart/canvas`',
    imports: ['Group'],
    layers: { Group: 'canvas' },
  },
  {
    name: 'Group.html',
    group: 'Components',
    description: 'Standalone Group from `layerchart/html`',
    imports: ['Group'],
    layers: { Group: 'html' },
  },
  {
    name: 'Pattern',
    group: 'Components',
    description: 'Standalone Pattern (agnostic) — baseline',
    imports: ['Pattern'],
  },
  {
    name: 'Pattern.svg',
    group: 'Components',
    description: 'Standalone Pattern from `layerchart/svg`',
    imports: ['Pattern'],
    layers: { Pattern: 'svg' },
  },
  {
    name: 'Pattern.canvas',
    group: 'Components',
    description: 'Standalone Pattern from `layerchart/canvas`',
    imports: ['Pattern'],
    layers: { Pattern: 'canvas' },
  },
  {
    name: 'Pattern.html',
    group: 'Components',
    description: 'Standalone Pattern from `layerchart/html`',
    imports: ['Pattern'],
    layers: { Pattern: 'html' },
  },
  {
    name: 'Ellipse',
    group: 'Components',
    description: 'Standalone Ellipse (agnostic) — baseline',
    imports: ['Ellipse'],
  },
  {
    name: 'Ellipse.svg',
    group: 'Components',
    description: 'Standalone Ellipse from `layerchart/svg`',
    imports: ['Ellipse'],
    layers: { Ellipse: 'svg' },
  },
  {
    name: 'Ellipse.canvas',
    group: 'Components',
    description: 'Standalone Ellipse from `layerchart/canvas`',
    imports: ['Ellipse'],
    layers: { Ellipse: 'canvas' },
  },
  {
    name: 'Ellipse.html',
    group: 'Components',
    description: 'Standalone Ellipse from `layerchart/html`',
    imports: ['Ellipse'],
    layers: { Ellipse: 'html' },
  },
  {
    name: 'Polygon',
    group: 'Components',
    description: 'Standalone Polygon (agnostic) — baseline',
    imports: ['Polygon'],
  },
  {
    name: 'Polygon.svg',
    group: 'Components',
    description: 'Standalone Polygon from `layerchart/svg`',
    imports: ['Polygon'],
    layers: { Polygon: 'svg' },
  },
  {
    name: 'Polygon.canvas',
    group: 'Components',
    description: 'Standalone Polygon from `layerchart/canvas`',
    imports: ['Polygon'],
    layers: { Polygon: 'canvas' },
  },
  {
    name: 'Image',
    group: 'Components',
    description: 'Standalone Image (agnostic) — baseline',
    imports: ['Image'],
  },
  {
    name: 'Image.svg',
    group: 'Components',
    description: 'Standalone Image from `layerchart/svg`',
    imports: ['Image'],
    layers: { Image: 'svg' },
  },
  {
    name: 'Image.canvas',
    group: 'Components',
    description: 'Standalone Image from `layerchart/canvas`',
    imports: ['Image'],
    layers: { Image: 'canvas' },
  },
  {
    name: 'Image.html',
    group: 'Components',
    description: 'Standalone Image from `layerchart/html`',
    imports: ['Image'],
    layers: { Image: 'html' },
  },

  // Axis is a compound mark: pulls Group + Line + Text + Rule. The per-layer
  // variants use the corresponding per-layer Group/Line/Text directly. Measured
  // in isolation (without Chart) since `Chart`'s `ChartChildren` statically
  // imports the agnostic Axis variant.
  {
    name: 'Axis',
    group: 'Components',
    description: 'Standalone Axis (agnostic) — baseline',
    imports: ['Axis'],
  },
  {
    name: 'Axis.svg',
    group: 'Components',
    description: 'Standalone Axis from `layerchart/svg`',
    imports: ['Axis'],
    layers: { Axis: 'svg' },
  },
  {
    name: 'Axis.canvas',
    group: 'Components',
    description: 'Standalone Axis from `layerchart/canvas`',
    imports: ['Axis'],
    layers: { Axis: 'canvas' },
  },
  {
    name: 'Axis.html',
    group: 'Components',
    description: 'Standalone Axis from `layerchart/html`',
    imports: ['Axis'],
    layers: { Axis: 'html' },
  },

  // Rule is a compound mark: pulls Group + Line + Circle. Per-layer variants
  // use the corresponding per-layer primitives directly.
  {
    name: 'Rule',
    group: 'Components',
    description: 'Standalone Rule (agnostic) — baseline',
    imports: ['Rule'],
  },
  {
    name: 'Rule.svg',
    group: 'Components',
    description: 'Standalone Rule from `layerchart/svg`',
    imports: ['Rule'],
    layers: { Rule: 'svg' },
  },
  {
    name: 'Rule.canvas',
    group: 'Components',
    description: 'Standalone Rule from `layerchart/canvas`',
    imports: ['Rule'],
    layers: { Rule: 'canvas' },
  },
  {
    name: 'Rule.html',
    group: 'Components',
    description: 'Standalone Rule from `layerchart/html`',
    imports: ['Rule'],
    layers: { Rule: 'html' },
  },

  // Grid is a compound mark: pulls Group + Line + Circle + Rule. Per-layer
  // variants use the corresponding per-layer primitives directly.
  {
    name: 'Grid',
    group: 'Components',
    description: 'Standalone Grid (agnostic) — baseline',
    imports: ['Grid'],
  },
  {
    name: 'Grid.svg',
    group: 'Components',
    description: 'Standalone Grid from `layerchart/svg`',
    imports: ['Grid'],
    layers: { Grid: 'svg' },
  },
  {
    name: 'Grid.canvas',
    group: 'Components',
    description: 'Standalone Grid from `layerchart/canvas`',
    imports: ['Grid'],
    layers: { Grid: 'canvas' },
  },
  {
    name: 'Grid.html',
    group: 'Components',
    description: 'Standalone Grid from `layerchart/html`',
    imports: ['Grid'],
    layers: { Grid: 'html' },
  },

  // Highlight is a compound mark: pulls Circle + Line + Rect (+ Arc when
  // radial). Per-layer variants use the corresponding per-layer primitives.
  {
    name: 'Highlight',
    group: 'Components',
    description: 'Standalone Highlight (agnostic) — baseline',
    imports: ['Highlight'],
  },
  {
    name: 'Highlight.svg',
    group: 'Components',
    description: 'Standalone Highlight from `layerchart/svg`',
    imports: ['Highlight'],
    layers: { Highlight: 'svg' },
  },
  {
    name: 'Highlight.canvas',
    group: 'Components',
    description: 'Standalone Highlight from `layerchart/canvas`',
    imports: ['Highlight'],
    layers: { Highlight: 'canvas' },
  },
  {
    name: 'Highlight.html',
    group: 'Components',
    description: 'Standalone Highlight from `layerchart/html`',
    imports: ['Highlight'],
    layers: { Highlight: 'html' },
  },

  // RectClipPath / ChartClipPath chain pulls ClipPath. Per-layer variants
  // use the corresponding per-layer ClipPath directly.
  {
    name: 'RectClipPath',
    group: 'Components',
    description: 'Standalone RectClipPath (agnostic) — baseline',
    imports: ['RectClipPath'],
  },
  {
    name: 'RectClipPath.svg',
    group: 'Components',
    description: 'Standalone RectClipPath from `layerchart/svg`',
    imports: ['RectClipPath'],
    layers: { RectClipPath: 'svg' },
  },
  {
    name: 'RectClipPath.canvas',
    group: 'Components',
    description: 'Standalone RectClipPath from `layerchart/canvas`',
    imports: ['RectClipPath'],
    layers: { RectClipPath: 'canvas' },
  },
  {
    name: 'RectClipPath.html',
    group: 'Components',
    description: 'Standalone RectClipPath from `layerchart/html`',
    imports: ['RectClipPath'],
    layers: { RectClipPath: 'html' },
  },
  {
    name: 'ChartClipPath',
    group: 'Components',
    description: 'Standalone ChartClipPath (agnostic) — baseline',
    imports: ['ChartClipPath'],
  },
  {
    name: 'ChartClipPath.svg',
    group: 'Components',
    description: 'Standalone ChartClipPath from `layerchart/svg`',
    imports: ['ChartClipPath'],
    layers: { ChartClipPath: 'svg' },
  },
  {
    name: 'ChartClipPath.canvas',
    group: 'Components',
    description: 'Standalone ChartClipPath from `layerchart/canvas`',
    imports: ['ChartClipPath'],
    layers: { ChartClipPath: 'canvas' },
  },
  {
    name: 'ChartClipPath.html',
    group: 'Components',
    description: 'Standalone ChartClipPath from `layerchart/html`',
    imports: ['ChartClipPath'],
    layers: { ChartClipPath: 'html' },
  },

  // Arc / Spline / Area are heavy compound marks built on Path. Per-layer
  // variants use the corresponding per-layer Path directly. (Arc has no html
  // variant since it renders SVG path geometry.)
  {
    name: 'Arc',
    group: 'Components',
    description: 'Standalone Arc (agnostic) — baseline',
    imports: ['Arc'],
  },
  {
    name: 'Arc.svg',
    group: 'Components',
    description: 'Standalone Arc from `layerchart/svg`',
    imports: ['Arc'],
    layers: { Arc: 'svg' },
  },
  {
    name: 'Arc.canvas',
    group: 'Components',
    description: 'Standalone Arc from `layerchart/canvas`',
    imports: ['Arc'],
    layers: { Arc: 'canvas' },
  },
  {
    name: 'Spline',
    group: 'Components',
    description: 'Standalone Spline (agnostic) — baseline',
    imports: ['Spline'],
  },
  {
    name: 'Spline.svg',
    group: 'Components',
    description: 'Standalone Spline from `layerchart/svg`',
    imports: ['Spline'],
    layers: { Spline: 'svg' },
  },
  {
    name: 'Spline.canvas',
    group: 'Components',
    description: 'Standalone Spline from `layerchart/canvas`',
    imports: ['Spline'],
    layers: { Spline: 'canvas' },
  },
  {
    name: 'Area',
    group: 'Components',
    description: 'Standalone Area (agnostic) — baseline',
    imports: ['Area'],
  },
  {
    name: 'Area.svg',
    group: 'Components',
    description: 'Standalone Area from `layerchart/svg`',
    imports: ['Area'],
    layers: { Area: 'svg' },
  },
  {
    name: 'Area.canvas',
    group: 'Components',
    description: 'Standalone Area from `layerchart/canvas`',
    imports: ['Area'],
    layers: { Area: 'canvas' },
  },

  // Pie / ArcLabel / Bar / Bars / Points / Labels — heavy compounds built on
  // primitives. Per-layer variants use the corresponding per-layer primitives.
  {
    name: 'Pie',
    group: 'Components',
    description: 'Standalone Pie (agnostic) — baseline',
    imports: ['Pie'],
  },
  {
    name: 'Pie.svg',
    group: 'Components',
    description: 'Standalone Pie from `layerchart/svg`',
    imports: ['Pie'],
    layers: { Pie: 'svg' },
  },
  {
    name: 'Pie.canvas',
    group: 'Components',
    description: 'Standalone Pie from `layerchart/canvas`',
    imports: ['Pie'],
    layers: { Pie: 'canvas' },
  },
  {
    name: 'ArcLabel',
    group: 'Components',
    description: 'Standalone ArcLabel (agnostic) — baseline',
    imports: ['ArcLabel'],
  },
  {
    name: 'ArcLabel.svg',
    group: 'Components',
    description: 'Standalone ArcLabel from `layerchart/svg`',
    imports: ['ArcLabel'],
    layers: { ArcLabel: 'svg' },
  },
  {
    name: 'ArcLabel.canvas',
    group: 'Components',
    description: 'Standalone ArcLabel from `layerchart/canvas`',
    imports: ['ArcLabel'],
    layers: { ArcLabel: 'canvas' },
  },
  {
    name: 'Bar',
    group: 'Components',
    description: 'Standalone Bar (agnostic) — baseline',
    imports: ['Bar'],
  },
  {
    name: 'Bar.svg',
    group: 'Components',
    description: 'Standalone Bar from `layerchart/svg`',
    imports: ['Bar'],
    layers: { Bar: 'svg' },
  },
  {
    name: 'Bar.canvas',
    group: 'Components',
    description: 'Standalone Bar from `layerchart/canvas`',
    imports: ['Bar'],
    layers: { Bar: 'canvas' },
  },
  {
    name: 'Bars',
    group: 'Components',
    description: 'Standalone Bars (agnostic) — baseline',
    imports: ['Bars'],
  },
  {
    name: 'Bars.svg',
    group: 'Components',
    description: 'Standalone Bars from `layerchart/svg`',
    imports: ['Bars'],
    layers: { Bars: 'svg' },
  },
  {
    name: 'Bars.canvas',
    group: 'Components',
    description: 'Standalone Bars from `layerchart/canvas`',
    imports: ['Bars'],
    layers: { Bars: 'canvas' },
  },
  {
    name: 'Points',
    group: 'Components',
    description: 'Standalone Points (agnostic) — baseline',
    imports: ['Points'],
  },
  {
    name: 'Points.svg',
    group: 'Components',
    description: 'Standalone Points from `layerchart/svg`',
    imports: ['Points'],
    layers: { Points: 'svg' },
  },
  {
    name: 'Points.canvas',
    group: 'Components',
    description: 'Standalone Points from `layerchart/canvas`',
    imports: ['Points'],
    layers: { Points: 'canvas' },
  },
  {
    name: 'Points.html',
    group: 'Components',
    description: 'Standalone Points from `layerchart/html`',
    imports: ['Points'],
    layers: { Points: 'html' },
  },
  {
    name: 'Labels',
    group: 'Components',
    description: 'Standalone Labels (agnostic) — baseline',
    imports: ['Labels'],
  },
  {
    name: 'Labels.svg',
    group: 'Components',
    description: 'Standalone Labels from `layerchart/svg`',
    imports: ['Labels'],
    layers: { Labels: 'svg' },
  },
  {
    name: 'Labels.canvas',
    group: 'Components',
    description: 'Standalone Labels from `layerchart/canvas`',
    imports: ['Labels'],
    layers: { Labels: 'canvas' },
  },
  {
    name: 'Labels.html',
    group: 'Components',
    description: 'Standalone Labels from `layerchart/html`',
    imports: ['Labels'],
    layers: { Labels: 'html' },
  },

  // Niche compounds.
  {
    name: 'Frame',
    group: 'Components',
    description: 'Standalone Frame (agnostic) — baseline',
    imports: ['Frame'],
  },
  {
    name: 'Frame.svg',
    group: 'Components',
    description: 'Standalone Frame from `layerchart/svg`',
    imports: ['Frame'],
    layers: { Frame: 'svg' },
  },
  {
    name: 'Frame.canvas',
    group: 'Components',
    description: 'Standalone Frame from `layerchart/canvas`',
    imports: ['Frame'],
    layers: { Frame: 'canvas' },
  },
  {
    name: 'Frame.html',
    group: 'Components',
    description: 'Standalone Frame from `layerchart/html`',
    imports: ['Frame'],
    layers: { Frame: 'html' },
  },
  {
    name: 'Cell',
    group: 'Components',
    description: 'Standalone Cell (agnostic) — baseline',
    imports: ['Cell'],
  },
  {
    name: 'Cell.svg',
    group: 'Components',
    description: 'Standalone Cell from `layerchart/svg`',
    imports: ['Cell'],
    layers: { Cell: 'svg' },
  },
  {
    name: 'Cell.canvas',
    group: 'Components',
    description: 'Standalone Cell from `layerchart/canvas`',
    imports: ['Cell'],
    layers: { Cell: 'canvas' },
  },
  {
    name: 'Cell.html',
    group: 'Components',
    description: 'Standalone Cell from `layerchart/html`',
    imports: ['Cell'],
    layers: { Cell: 'html' },
  },
  {
    name: 'Threshold',
    group: 'Components',
    description: 'Standalone Threshold (agnostic) — baseline',
    imports: ['Threshold'],
  },
  {
    name: 'Threshold.svg',
    group: 'Components',
    description: 'Standalone Threshold from `layerchart/svg`',
    imports: ['Threshold'],
    layers: { Threshold: 'svg' },
  },
  {
    name: 'Threshold.canvas',
    group: 'Components',
    description: 'Standalone Threshold from `layerchart/canvas`',
    imports: ['Threshold'],
    layers: { Threshold: 'canvas' },
  },
  {
    name: 'AnnotationLine',
    group: 'Components',
    description: 'Standalone AnnotationLine (agnostic) — baseline',
    imports: ['AnnotationLine'],
  },
  {
    name: 'AnnotationLine.svg',
    group: 'Components',
    description: 'Standalone AnnotationLine from `layerchart/svg`',
    imports: ['AnnotationLine'],
    layers: { AnnotationLine: 'svg' },
  },
  {
    name: 'AnnotationLine.canvas',
    group: 'Components',
    description: 'Standalone AnnotationLine from `layerchart/canvas`',
    imports: ['AnnotationLine'],
    layers: { AnnotationLine: 'canvas' },
  },
  {
    name: 'AnnotationPoint',
    group: 'Components',
    description: 'Standalone AnnotationPoint (agnostic) — baseline',
    imports: ['AnnotationPoint'],
  },
  {
    name: 'AnnotationPoint.svg',
    group: 'Components',
    description: 'Standalone AnnotationPoint from `layerchart/svg`',
    imports: ['AnnotationPoint'],
    layers: { AnnotationPoint: 'svg' },
  },
  {
    name: 'AnnotationPoint.canvas',
    group: 'Components',
    description: 'Standalone AnnotationPoint from `layerchart/canvas`',
    imports: ['AnnotationPoint'],
    layers: { AnnotationPoint: 'canvas' },
  },
  {
    name: 'Trail',
    group: 'Components',
    description: 'Standalone Trail (agnostic) — baseline',
    imports: ['Trail'],
  },
  {
    name: 'Trail.svg',
    group: 'Components',
    description: 'Standalone Trail from `layerchart/svg`',
    imports: ['Trail'],
    layers: { Trail: 'svg' },
  },
  {
    name: 'Trail.canvas',
    group: 'Components',
    description: 'Standalone Trail from `layerchart/canvas`',
    imports: ['Trail'],
    layers: { Trail: 'canvas' },
  },

  {
    name: 'Vector',
    group: 'Components',
    description: 'Standalone Vector (agnostic) — baseline',
    imports: ['Vector'],
  },
  {
    name: 'Vector.svg',
    group: 'Components',
    description: 'Standalone Vector from `layerchart/svg`',
    imports: ['Vector'],
    layers: { Vector: 'svg' },
  },
  {
    name: 'Vector.canvas',
    group: 'Components',
    description: 'Standalone Vector from `layerchart/canvas`',
    imports: ['Vector'],
    layers: { Vector: 'canvas' },
  },
  {
    name: 'Link',
    group: 'Components',
    description: 'Standalone Link (agnostic) — baseline',
    imports: ['Link'],
  },
  {
    name: 'Link.svg',
    group: 'Components',
    description: 'Standalone Link from `layerchart/svg`',
    imports: ['Link'],
    layers: { Link: 'svg' },
  },
  {
    name: 'Link.canvas',
    group: 'Components',
    description: 'Standalone Link from `layerchart/canvas`',
    imports: ['Link'],
    layers: { Link: 'canvas' },
  },
  {
    name: 'AnnotationRange',
    group: 'Components',
    description: 'Standalone AnnotationRange (agnostic) — baseline',
    imports: ['AnnotationRange'],
  },
  {
    name: 'AnnotationRange.svg',
    group: 'Components',
    description: 'Standalone AnnotationRange from `layerchart/svg`',
    imports: ['AnnotationRange'],
    layers: { AnnotationRange: 'svg' },
  },
  {
    name: 'AnnotationRange.canvas',
    group: 'Components',
    description: 'Standalone AnnotationRange from `layerchart/canvas`',
    imports: ['AnnotationRange'],
    layers: { AnnotationRange: 'canvas' },
  },
  {
    name: 'Hull',
    group: 'Components',
    description: 'Standalone Hull (agnostic) — baseline',
    imports: ['Hull'],
  },
  {
    name: 'Hull.svg',
    group: 'Components',
    description: 'Standalone Hull from `layerchart/svg`',
    imports: ['Hull'],
    layers: { Hull: 'svg' },
  },
  {
    name: 'Hull.canvas',
    group: 'Components',
    description: 'Standalone Hull from `layerchart/canvas`',
    imports: ['Hull'],
    layers: { Hull: 'canvas' },
  },
  {
    name: 'Density',
    group: 'Components',
    description: 'Standalone Density (agnostic) — baseline',
    imports: ['Density'],
  },
  {
    name: 'Density.svg',
    group: 'Components',
    description: 'Standalone Density from `layerchart/svg`',
    imports: ['Density'],
    layers: { Density: 'svg' },
  },
  {
    name: 'Density.canvas',
    group: 'Components',
    description: 'Standalone Density from `layerchart/canvas`',
    imports: ['Density'],
    layers: { Density: 'canvas' },
  },
  {
    name: 'Calendar',
    group: 'Components',
    description: 'Standalone Calendar (agnostic) — baseline',
    imports: ['Calendar'],
  },
  {
    name: 'Calendar.svg',
    group: 'Components',
    description: 'Standalone Calendar from `layerchart/svg`',
    imports: ['Calendar'],
    layers: { Calendar: 'svg' },
  },
  {
    name: 'Calendar.canvas',
    group: 'Components',
    description: 'Standalone Calendar from `layerchart/canvas`',
    imports: ['Calendar'],
    layers: { Calendar: 'canvas' },
  },
  {
    name: 'CircleClipPath',
    group: 'Components',
    description: 'Standalone CircleClipPath (agnostic) — baseline',
    imports: ['CircleClipPath'],
  },
  {
    name: 'CircleClipPath.svg',
    group: 'Components',
    description: 'Standalone CircleClipPath from `layerchart/svg`',
    imports: ['CircleClipPath'],
    layers: { CircleClipPath: 'svg' },
  },
  {
    name: 'CircleClipPath.canvas',
    group: 'Components',
    description: 'Standalone CircleClipPath from `layerchart/canvas`',
    imports: ['CircleClipPath'],
    layers: { CircleClipPath: 'canvas' },
  },
  {
    name: 'CircleClipPath.html',
    group: 'Components',
    description: 'Standalone CircleClipPath from `layerchart/html`',
    imports: ['CircleClipPath'],
    layers: { CircleClipPath: 'html' },
  },

  {
    name: 'Voronoi',
    group: 'Components',
    description: 'Standalone Voronoi (agnostic) — baseline',
    imports: ['Voronoi'],
  },
  {
    name: 'Voronoi.svg',
    group: 'Components',
    description: 'Standalone Voronoi from `layerchart/svg`',
    imports: ['Voronoi'],
    layers: { Voronoi: 'svg' },
  },
  {
    name: 'Voronoi.canvas',
    group: 'Components',
    description: 'Standalone Voronoi from `layerchart/canvas`',
    imports: ['Voronoi'],
    layers: { Voronoi: 'canvas' },
  },
  {
    name: 'Contour',
    group: 'Components',
    description: 'Standalone Contour (agnostic) — baseline',
    imports: ['Contour'],
  },
  {
    name: 'Contour.svg',
    group: 'Components',
    description: 'Standalone Contour from `layerchart/svg`',
    imports: ['Contour'],
    layers: { Contour: 'svg' },
  },
  {
    name: 'Contour.canvas',
    group: 'Components',
    description: 'Standalone Contour from `layerchart/canvas`',
    imports: ['Contour'],
    layers: { Contour: 'canvas' },
  },
  {
    name: 'Month',
    group: 'Components',
    description: 'Standalone Month (agnostic) — baseline',
    imports: ['Month'],
  },
  {
    name: 'Month.svg',
    group: 'Components',
    description: 'Standalone Month from `layerchart/svg`',
    imports: ['Month'],
    layers: { Month: 'svg' },
  },
  {
    name: 'Month.canvas',
    group: 'Components',
    description: 'Standalone Month from `layerchart/canvas`',
    imports: ['Month'],
    layers: { Month: 'canvas' },
  },
  {
    name: 'Raster',
    group: 'Components',
    description: 'Standalone Raster (agnostic) — baseline',
    imports: ['Raster'],
  },
  {
    name: 'Raster.svg',
    group: 'Components',
    description: 'Standalone Raster from `layerchart/svg`',
    imports: ['Raster'],
    layers: { Raster: 'svg' },
  },
  {
    name: 'Raster.canvas',
    group: 'Components',
    description: 'Standalone Raster from `layerchart/canvas`',
    imports: ['Raster'],
    layers: { Raster: 'canvas' },
  },
  {
    name: 'Raster.html',
    group: 'Components',
    description: 'Standalone Raster from `layerchart/html`',
    imports: ['Raster'],
    layers: { Raster: 'html' },
  },
  {
    name: 'Violin',
    group: 'Components',
    description: 'Standalone Violin (agnostic) — baseline',
    imports: ['Violin'],
  },
  {
    name: 'Violin.svg',
    group: 'Components',
    description: 'Standalone Violin from `layerchart/svg`',
    imports: ['Violin'],
    layers: { Violin: 'svg' },
  },
  {
    name: 'Violin.canvas',
    group: 'Components',
    description: 'Standalone Violin from `layerchart/canvas`',
    imports: ['Violin'],
    layers: { Violin: 'canvas' },
  },
  {
    name: 'BoxPlot',
    group: 'Components',
    description: 'Standalone BoxPlot (agnostic) — baseline',
    imports: ['BoxPlot'],
  },
  {
    name: 'BoxPlot.svg',
    group: 'Components',
    description: 'Standalone BoxPlot from `layerchart/svg`',
    imports: ['BoxPlot'],
    layers: { BoxPlot: 'svg' },
  },
  {
    name: 'BoxPlot.canvas',
    group: 'Components',
    description: 'Standalone BoxPlot from `layerchart/canvas`',
    imports: ['BoxPlot'],
    layers: { BoxPlot: 'canvas' },
  },

  // Geo components
  {
    name: 'GeoPath',
    group: 'Components',
    description: 'Standalone GeoPath (agnostic) — baseline',
    imports: ['GeoPath'],
  },
  {
    name: 'GeoPath.svg',
    group: 'Components',
    description: 'Standalone GeoPath from `layerchart/svg`',
    imports: ['GeoPath'],
    layers: { GeoPath: 'svg' },
  },
  {
    name: 'GeoPath.canvas',
    group: 'Components',
    description: 'Standalone GeoPath from `layerchart/canvas`',
    imports: ['GeoPath'],
    layers: { GeoPath: 'canvas' },
  },
  {
    name: 'GeoSpline',
    group: 'Components',
    description: 'Standalone GeoSpline (agnostic) — baseline',
    imports: ['GeoSpline'],
  },
  {
    name: 'GeoSpline.svg',
    group: 'Components',
    description: 'Standalone GeoSpline from `layerchart/svg`',
    imports: ['GeoSpline'],
    layers: { GeoSpline: 'svg' },
  },
  {
    name: 'GeoSpline.canvas',
    group: 'Components',
    description: 'Standalone GeoSpline from `layerchart/canvas`',
    imports: ['GeoSpline'],
    layers: { GeoSpline: 'canvas' },
  },
  {
    name: 'GeoPoint',
    group: 'Components',
    description: 'Standalone GeoPoint (agnostic) — baseline',
    imports: ['GeoPoint'],
  },
  {
    name: 'GeoPoint.svg',
    group: 'Components',
    description: 'Standalone GeoPoint from `layerchart/svg`',
    imports: ['GeoPoint'],
    layers: { GeoPoint: 'svg' },
  },
  {
    name: 'GeoPoint.canvas',
    group: 'Components',
    description: 'Standalone GeoPoint from `layerchart/canvas`',
    imports: ['GeoPoint'],
    layers: { GeoPoint: 'canvas' },
  },
  {
    name: 'GeoCircle',
    group: 'Components',
    description: 'Standalone GeoCircle (agnostic) — baseline',
    imports: ['GeoCircle'],
  },
  {
    name: 'GeoCircle.svg',
    group: 'Components',
    description: 'Standalone GeoCircle from `layerchart/svg`',
    imports: ['GeoCircle'],
    layers: { GeoCircle: 'svg' },
  },
  {
    name: 'GeoCircle.canvas',
    group: 'Components',
    description: 'Standalone GeoCircle from `layerchart/canvas`',
    imports: ['GeoCircle'],
    layers: { GeoCircle: 'canvas' },
  },
  {
    name: 'GeoTile',
    group: 'Components',
    description: 'Standalone GeoTile (agnostic) — baseline',
    imports: ['GeoTile'],
  },
  {
    name: 'GeoTile.svg',
    group: 'Components',
    description: 'Standalone GeoTile from `layerchart/svg`',
    imports: ['GeoTile'],
    layers: { GeoTile: 'svg' },
  },
  {
    name: 'GeoTile.canvas',
    group: 'Components',
    description: 'Standalone GeoTile from `layerchart/canvas`',
    imports: ['GeoTile'],
    layers: { GeoTile: 'canvas' },
  },
  {
    name: 'TileImage',
    group: 'Components',
    description: 'Standalone TileImage (agnostic) — baseline',
    imports: ['TileImage'],
  },
  {
    name: 'TileImage.svg',
    group: 'Components',
    description: 'Standalone TileImage from `layerchart/svg`',
    imports: ['TileImage'],
    layers: { TileImage: 'svg' },
  },
  {
    name: 'TileImage.canvas',
    group: 'Components',
    description: 'Standalone TileImage from `layerchart/canvas`',
    imports: ['TileImage'],
    layers: { TileImage: 'canvas' },
  },
  {
    name: 'Graticule',
    group: 'Components',
    description: 'Standalone Graticule (agnostic) — baseline',
    imports: ['Graticule'],
  },
  {
    name: 'Graticule.svg',
    group: 'Components',
    description: 'Standalone Graticule from `layerchart/svg`',
    imports: ['Graticule'],
    layers: { Graticule: 'svg' },
  },
  {
    name: 'Graticule.canvas',
    group: 'Components',
    description: 'Standalone Graticule from `layerchart/canvas`',
    imports: ['Graticule'],
    layers: { Graticule: 'canvas' },
  },
  {
    name: 'GeoClipPath',
    group: 'Components',
    description: 'Standalone GeoClipPath (agnostic) — baseline',
    imports: ['GeoClipPath'],
  },
  {
    name: 'GeoClipPath.svg',
    group: 'Components',
    description: 'Standalone GeoClipPath from `layerchart/svg`',
    imports: ['GeoClipPath'],
    layers: { GeoClipPath: 'svg' },
  },
  {
    name: 'GeoClipPath.canvas',
    group: 'Components',
    description: 'Standalone GeoClipPath from `layerchart/canvas`',
    imports: ['GeoClipPath'],
    layers: { GeoClipPath: 'canvas' },
  },
  {
    name: 'GeoEdgeFade',
    group: 'Components',
    description: 'Standalone GeoEdgeFade (agnostic) — baseline',
    imports: ['GeoEdgeFade'],
  },
  {
    name: 'GeoEdgeFade.svg',
    group: 'Components',
    description: 'Standalone GeoEdgeFade from `layerchart/svg`',
    imports: ['GeoEdgeFade'],
    layers: { GeoEdgeFade: 'svg' },
  },
  {
    name: 'GeoEdgeFade.canvas',
    group: 'Components',
    description: 'Standalone GeoEdgeFade from `layerchart/canvas`',
    imports: ['GeoEdgeFade'],
    layers: { GeoEdgeFade: 'canvas' },
  },

  // --- Worst case ---
  {
    name: 'all',
    group: 'Worst case',
    description: 'Everything from layerchart (worst case)',
    imports: ['*'],
  },
];

/**
 * Individual components to measure in isolation.
 * Auto-extracted from the layerchart components index.
 */
const INDIVIDUAL_COMPONENTS: string[] = [
  'AnnotationLine',
  'AnnotationPoint',
  'AnnotationRange',
  'Arc',
  'ArcLabel',
  'Area',
  'Axis',
  'Bar',
  'Bars',
  'Blur',
  'BoxPlot',
  'Bounds',
  'BrushContext',
  'Calendar',
  'Canvas',
  'Cell',
  'Chart',
  'ChartCore',
  'Chord',
  'ChartClipPath',
  'Circle',
  'CircleClipPath',
  'CircleLegend',
  'ClipPath',
  'ColorRamp',
  'Connector',
  'Contour',
  'Dagre',
  'Density',
  'Ellipse',
  'ForceSimulation',
  'Frame',
  'GeoCircle',
  'GeoEdgeFade',
  'GeoLegend',
  'GeoPath',
  'GeoPoint',
  'GeoProjection',
  'GeoRaster',
  'GeoSpline',
  'GeoTile',
  'GeoVisible',
  'Graticule',
  'Grid',
  'Group',
  'Highlight',
  'Html',
  'Hull',
  'Image',
  'Labels',
  'Layer',
  'Legend',
  'Line',
  'LinearGradient',
  'Link',
  'Month',
  'MotionPath',
  'Pack',
  'Partition',
  'Path',
  'Pattern',
  'Pie',
  'Point',
  'Points',
  'Polygon',
  'RadialGradient',
  'Raster',
  'Rect',
  'RectClipPath',
  'Ribbon',
  'Rule',
  'Sankey',
  'Spline',
  'Svg',
  'Text',
  'Threshold',
  'TileImage',
  'Tooltip',
  'TransformContext',
  'Trail',
  'Tree',
  'Treemap',
  'Vector',
  'Violin',
  'Voronoi',
  'WebGL',
];

export function getScenarios(filter?: string[]): Scenario[] {
  if (!filter) return scenarios;
  return scenarios.filter((s) => filter.includes(s.name));
}

export function getComponentScenarios(filter?: string[]): Scenario[] {
  const components = filter
    ? INDIVIDUAL_COMPONENTS.filter((c) => filter.includes(c))
    : INDIVIDUAL_COMPONENTS;

  return components.map((name) => ({
    name: `component:${name}`,
    description: `Individual component: ${name}`,
    imports: [name],
  }));
}
