import { prerender } from '$app/server';
import { env } from '$env/dynamic/private';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { FEATURED_SITES, HIGHLIGHTED_SITES, TIER_LEVELS } from './dependents-overrides';
import { SPONSOR_OVERRIDES } from './dependents-overrides';

export type Dependent = {
	name?: string;
	reponame?: string;
	owner?: string;
	description?: string;
	repourl?: string;
	homepageurl?: string;
	showcaseurl?: string;
	stars?: number;
	noregenerate?: boolean;
	tierOverride?: string;
};

const POPULAR_STAR_THRESHOLD = 100;
const OTHER_STAR_THRESHOLD = 10;

function writeShowcaseData(data: Record<string, Dependent[]>) {
	const __dirname = dirname(fileURLToPath(import.meta.url));
	const entries = Object.entries(data)
		.map(
			([key, value]) =>
				`export const ${key}: Dependent[] = ${JSON.stringify(value.filter((d) => d.description && d.homepageurl), null, '\t')};`
		)
		.join('\n\n');
	writeFileSync(
		join(__dirname, 'showcase.ts'),
		`// Auto-generated by dependency.remote.ts — do not edit manually\n// Facilitates viewing of data, and used for showcase hero image generation.\n\n` +
			`import type { Dependent } from './dependency.remote';\n\n` +
			entries +
			'\n'
	);
	console.log(`[getDependents] Wrote showcase.ts`);
}

export const getDependents = prerender(async () => {
	const featuredSites = [...FEATURED_SITES];

	const highlightedSites = [...HIGHLIGHTED_SITES];

	const githubHeaders: Record<string, string> = {
		Accept: 'application/vnd.github.v3+json',
		'User-Agent': 'LayerChart docs'
	};

	if (env.GITHUB_API_TOKEN) {
		const prefix = env.GITHUB_API_TOKEN.startsWith('ghp_') ? 'token' : 'Bearer';
		githubHeaders['Authorization'] = `${prefix} ${env.GITHUB_API_TOKEN}`;
	}

	const totalStart = performance.now();

	// Step 1: Find repos with "layerchart" in package.json via code search
	// NOTE: Code search API has a strict rate limit, so pages are fetched sequentially
	const repoSet = new Set<string>();
	let page = 1;
	const perPage = 100;

	const step1Start = performance.now();
	while (true) {
		const searchUrl = `https://api.github.com/search/code?q=${encodeURIComponent('"layerchart" filename:package.json')}&per_page=${perPage}&page=${page}`;
		const res = await fetch(searchUrl, { headers: githubHeaders });

		if (!res.ok) {
			console.error(`GitHub code search failed: ${res.status} ${res.statusText}`);
			break;
		}

		const data = await res.json();
		const items = data.items ?? [];

		for (const item of items) {
			const fullName = item.repository?.full_name;
			if (fullName && fullName !== 'techniq/layerchart') {
				repoSet.add(fullName);
			}
		}

		if (items.length < perPage || repoSet.size >= data.total_count) break;
		page++;
	}
	console.log(
		`[getDependents] Step 1 - Code search: ${((performance.now() - step1Start) / 1000).toFixed(2)}s (${repoSet.size} repos found, ${page} pages)`
	);

	// Step 2: Batch-fetch repo details via GitHub GraphQL (parallel)
	const step2Start = performance.now();
	const repos = [...repoSet];
	const batchSize = 50;

	const batchPromises = [];
	for (let i = 0; i < repos.length; i += batchSize) {
		const batch = repos.slice(i, i + batchSize);
		const fragments = batch
			.map((fullName, idx) => {
				const [owner, name] = fullName.split('/');
				return `repo${idx}: repository(owner: ${JSON.stringify(owner)}, name: ${JSON.stringify(name)}) { stargazerCount description homepageUrl url owner { login } name }`;
			})
			.join('\n');

		batchPromises.push(
			fetch('https://api.github.com/graphql', {
				method: 'POST',
				headers: githubHeaders,
				body: JSON.stringify({ query: `{ ${fragments} }` })
			}).then(async (res) => {
				if (!res.ok) return [];
				const { data } = await res.json();
				if (!data) return [];
				return Object.values(data)
					.filter(Boolean)
					.map((repo: any) => ({
						owner: repo.owner.login,
						reponame: repo.name,
						description: repo.description || null,
						repourl: repo.url,
						homepageurl: repo.homepageUrl || null,
						stars: repo.stargazerCount
					}));
			})
		);
	}

	const batchResults = await Promise.all(batchPromises);
	const dependents: Dependent[] = batchResults.flat();

	console.log(
		`[getDependents] Step 2 - GraphQL details: ${((performance.now() - step2Start) / 1000).toFixed(2)}s (${dependents.length} repos, ${batchPromises.length} batches)`
	);

	// Step 2.5: Fetch active sponsor logins+tiers and partition dependents into sponsorSites
	const step25Start = performance.now();

	// Map login (lowercase) → tier rank (lower = higher tier)
	const sponsorTierRank = new Map<string, number>();
	if (env.GITHUB_API_TOKEN) {
		try {
			const res = await fetch('https://api.github.com/graphql', {
				method: 'POST',
				headers: githubHeaders,
				body: JSON.stringify({
					query: `{ user(login: "techniq") { sponsorshipsAsMaintainer(first: 100, activeOnly: true) { nodes { sponsorEntity { ... on User { login } ... on Organization { login } } tier { monthlyPriceInDollars } } } } }`
				})
			});
			if (res.ok) {
				const { data } = await res.json();
				const nodes = data?.user?.sponsorshipsAsMaintainer?.nodes ?? [];
				for (const node of nodes) {
					const login = node.sponsorEntity?.login;
					if (!login) continue;
					const price = node.tier?.monthlyPriceInDollars ?? 0;
					const level =
						SPONSOR_OVERRIDES[login.toLowerCase()]?.tierOverride ??
						TIER_LEVELS.find((t) => price >= t.min)?.level ??
						'Backers Level';
					const rank = TIER_LEVELS.findIndex((t) => t.level === level);
					sponsorTierRank.set(login.toLowerCase(), rank === -1 ? TIER_LEVELS.length : rank);
				}
			}
		} catch (e) {
			console.error('[getDependents] Failed to fetch sponsor logins:', e);
		}
	}
	const sponsorLogins = new Set(sponsorTierRank.keys());

	const tierRankOf = (d: Dependent) =>
		sponsorTierRank.get(d.owner?.toLowerCase() ?? '') ?? TIER_LEVELS.length;

	// Partition dependents: sponsor-owned repos become sponsorSites, rest continues as normal
	// Merge SPONSOR_OVERRIDES as base, dependent data layers on top
	const sponsorDependents = dependents
		.filter((d) => d.owner && sponsorLogins.has(d.owner.toLowerCase()))
		.map((d) => {
			const override = SPONSOR_OVERRIDES[d.owner!.toLowerCase()] ?? {};
			const nonNull = Object.fromEntries(Object.entries(d).filter(([, v]) => v != null));
			return { ...override, ...nonNull } as Dependent;
		})
		.sort((a, b) => tierRankOf(a) - tierRankOf(b) || (b.stars ?? 0) - (a.stars ?? 0));
	const nonSponsorDependents = dependents.filter(
		(d) => !d.owner || !sponsorLogins.has(d.owner.toLowerCase())
	);

	// For sponsors with no matching dependent repo, fetch their GitHub profile as fallback
	const matchedLogins = new Set(sponsorDependents.map((d) => d.owner?.toLowerCase()));
	const unmatchedSponsors = [...sponsorLogins].filter((login) => !matchedLogins.has(login));
	const fallbackSponsorSites: Dependent[] = (
		await Promise.all(
			unmatchedSponsors.map(async (login): Promise<Dependent | null> => {
				try {
					const res = await fetch(`https://api.github.com/users/${login}`, {
						headers: githubHeaders
					});
					const profile = res.ok ? await res.json() : null;
					if (!profile?.login) return null;
					return {
						...SPONSOR_OVERRIDES[login],
						name: profile.name || profile.login,
						owner: profile.login,
						description: (profile.bio || '') as string,
						repourl: profile.html_url,
						...(profile.blog ? { homepageurl: profile.blog } : {})
					};
				} catch (e) {
					console.error(`[getDependents] Failed to fetch profile for sponsor ${login}:`, e);
					return null;
				}
			})
		)
	).filter((d) => d !== null) as Dependent[];

	const sponsorSites: Dependent[] = [...sponsorDependents, ...fallbackSponsorSites].sort(
		(a, b) => tierRankOf(a) - tierRankOf(b) || (b.stars ?? 0) - (a.stars ?? 0)
	);

	console.log(
		`[getDependents] Step 2.5 - Sponsors: ${((performance.now() - step25Start) / 1000).toFixed(2)}s (${sponsorSites.length} sponsor sites from ${[...sponsorLogins].join(', ')})`
	);

	// Step 3: Fetch stars for manually-listed sites (featured, highlighted)
	const step3Start = performance.now();
	const manualSites = [...featuredSites, ...highlightedSites];
	const githubRepoPattern = /github\.com\/([^/]+)\/([^/]+)/;
	const manualSitesWithRepos = manualSites
		.map((site) => {
			const match = site.repourl?.match(githubRepoPattern);
			return match ? { site, owner: match[1], name: match[2] } : null;
		})
		.filter(Boolean) as { site: Dependent; owner: string; name: string }[];

	if (manualSitesWithRepos.length > 0) {
		const fragments = manualSitesWithRepos
			.map(
				({ owner, name }, idx) =>
					`manual${idx}: repository(owner: ${JSON.stringify(owner)}, name: ${JSON.stringify(name)}) { stargazerCount }`
			)
			.join('\n');

		try {
			const res = await fetch('https://api.github.com/graphql', {
				method: 'POST',
				headers: githubHeaders,
				body: JSON.stringify({ query: `{ ${fragments} }` })
			});
			if (res.ok) {
				const { data } = await res.json();
				if (data) {
					manualSitesWithRepos.forEach(({ site }, idx) => {
						const repo = data[`manual${idx}`];
						if (repo) {
							site.stars = repo.stargazerCount;
						}
					});
				}
			}
		} catch (e) {
			console.error('[getDependents] Failed to fetch stars for manual sites:', e);
		}
	}
	console.log(
		`[getDependents] Step 3 - Manual site stars: ${((performance.now() - step3Start) / 1000).toFixed(2)}s (${manualSitesWithRepos.length} repos)`
	);

	console.log(`[getDependents] Total: ${((performance.now() - totalStart) / 1000).toFixed(2)}s`);

	// Build a set of repo URLs and homepage URLs from manually-listed sites for deduplication
	const manualUrls = new Set(
		manualSites.flatMap((s) => [s.repourl, s.homepageurl].filter(Boolean))
	);

	const filteredDependents = nonSponsorDependents
		.filter((d) => !manualUrls.has(d.repourl) && !manualUrls.has(d.homepageurl))
		.sort((a, b) => (b.stars ?? 0) - (a.stars ?? 0));

	const popularSites = filteredDependents.filter((d) => (d.stars ?? 0) >= POPULAR_STAR_THRESHOLD);
	const otherSites = [
		...highlightedSites,
		...filteredDependents.filter(
			(d) => (d.stars ?? 0) >= OTHER_STAR_THRESHOLD && (d.stars ?? 0) < POPULAR_STAR_THRESHOLD
		)
	];

	const result = { featuredSites, sponsorSites, popularSites, otherSites };

	// write to showcase.ts file, this is used for the showcase hero image generation and easy review of data.
	writeShowcaseData(result);

	return result;
});
