// Auto-generated by dependency.remote.ts — do not edit manually
import type { Dependent } from './dependency.remote';

export const featuredSites: Dependent[] = [
	{
		"name": "Zipline AI",
		"description": "Features, context and embeddings for real-time AI/ML",
		"repourl": "https://github.com/zipline-ai",
		"homepageurl": "https://zipline.ai/"
	},
	{
		"name": "Github Analysis",
		"description": "Analyze your GitHub repositories and NPM packages",
		"repourl": "https://github.com/techniq/github-analysis",
		"homepageurl": "https://github.techniq.dev",
		"noregenerate": true,
		"stars": 6
	},
	{
		"name": "Strava Analysis",
		"description": "Analyze your Strava activities",
		"repourl": "https://github.com/techniq/strava-analysis",
		"homepageurl": "https://strava.techniq.dev",
		"noregenerate": true,
		"stars": 13
	}
];

export const supporterSites: Dependent[] = [
	{
		"name": "Tenzir",
		"description": "Open source data pipelines for security teams",
		"repourl": "https://github.com/tenzir",
		"homepageurl": "https://tenzir.com/"
	},
	{
		"name": "shadcn-svelte",
		"description": "shadcn/ui, but for Svelte.",
		"repourl": "https://github.com/huntabyte/shadcn-svelte",
		"homepageurl": "https://shadcn-svelte.com/",
		"stars": 8454
	},
	{
		"name": "Sky Zoo",
		"description": "Bluesky stats",
		"repourl": "https://github.com/jycouet/jyc.dev",
		"homepageurl": "https://skyzoo.blue/",
		"stars": 24
	}
];

export const popularSites: Dependent[] = [];

export const otherSites: Dependent[] = [
	{
		"name": "GEO audit",
		"description": "GEO / AI audit that tracks your visibility impact",
		"homepageurl": "https://www.geoaud.it/"
	},
	{
		"name": "RetireNumber",
		"description": "Get a second opinion on your retirement number.",
		"homepageurl": "https://retirenumber.com/"
	},
	{
		"name": "PowerOutage.com",
		"description": "Tracks, records, and aggregates power outage data across the World",
		"homepageurl": "https://poweroutage.com/"
	},
	{
		"name": "IOM UN Migration: Ukraine Regional Response",
		"description": "Needs, Intentions, and Border Crossings",
		"homepageurl": "https://dtm.iom.int/online-interactive-resources/ukraine-regional-response-dashboard/index.html"
	},
	{
		"name": "Loyola Chicago: Center for Criminal Justice",
		"description": "The First Year of the Pretrial Fairness Act",
		"homepageurl": "https://pfa-1yr.loyolaccj.org/"
	},
	{
		"name": "ftop",
		"description": "Comperative performance metrics for Fortnite islands",
		"homepageurl": "https://ftop.app/"
	},
	{
		"name": "Nocturne",
		"description": "A next-generation platform for diabetes management",
		"homepageurl": "https://nocturne.app/"
	}
];
