// Auto-generated by dependency.remote.ts — do not edit manually
// Facilitates viewing of data, and used for showcase hero image generation.

import type { Dependent } from './dependency.remote';

export const featuredSites: Dependent[] = [
	{
		"name": "Zipline AI",
		"description": "Features, context and embeddings for real-time AI/ML",
		"repourl": "https://github.com/zipline-ai",
		"homepageurl": "https://zipline.ai/"
	},
	{
		"name": "Github Analysis",
		"description": "Analyze your GitHub repositories and NPM packages",
		"repourl": "https://github.com/techniq/github-analysis",
		"homepageurl": "https://github.techniq.dev",
		"noregenerate": true,
		"stars": 6
	},
	{
		"name": "Strava Analysis",
		"description": "Analyze your Strava activities",
		"repourl": "https://github.com/techniq/strava-analysis",
		"homepageurl": "https://strava.techniq.dev",
		"noregenerate": true,
		"stars": 13
	}
];

export const sponsorSites: Dependent[] = [
	{
		"name": "Tenzir",
		"homepageurl": "https://tenzir.com",
		"tierOverride": "Silver Level",
		"owner": "tenzir",
		"description": "Open source data pipelines for security teams",
		"repourl": "https://github.com/tenzir"
	},
	{
		"homepageurl": "https://shadcn-svelte.com",
		"tierOverride": "Bronze Level",
		"owner": "huntabyte",
		"reponame": "shadcn-svelte",
		"description": "shadcn/ui, but for Svelte. ✨",
		"repourl": "https://github.com/huntabyte/shadcn-svelte",
		"stars": 8454
	},
	{
		"name": "Sky Zoo",
		"homepageurl": "https://skyzoo.blue/",
		"description": "Bluesky Stats",
		"tierOverride": "Bronze Level",
		"owner": "jycouet",
		"reponame": "jyc.dev",
		"repourl": "https://github.com/jycouet/jyc.dev",
		"stars": 24
	}
];

export const popularSites: Dependent[] = [
	{
		"owner": "rajnandan1",
		"reponame": "kener",
		"description": "Stunning status pages, batteries included!",
		"repourl": "https://github.com/rajnandan1/kener",
		"homepageurl": "https://kener.ing/",
		"stars": 4799
	},
	{
		"owner": "exceptionless",
		"reponame": "Exceptionless",
		"description": "Exceptionless application",
		"repourl": "https://github.com/exceptionless/Exceptionless",
		"homepageurl": "https://exceptionless.com",
		"stars": 2453
	},
	{
		"owner": "amtoaer",
		"reponame": "bili-sync",
		"description": "由 Rust & Tokio 驱动的哔哩哔哩同步工具",
		"repourl": "https://github.com/amtoaer/bili-sync",
		"homepageurl": "https://bili-sync.amto.cc",
		"stars": 2307
	},
	{
		"owner": "LogicLabs-OU",
		"reponame": "OpenArchiver",
		"description": "An open-source platform for legally compliant email archiving.",
		"repourl": "https://github.com/LogicLabs-OU/OpenArchiver",
		"homepageurl": "https://openarchiver.com",
		"stars": 1800
	},
	{
		"owner": "javedh-dev",
		"reponame": "tracktor",
		"description": "Vehicle Tracking Management System",
		"repourl": "https://github.com/javedh-dev/tracktor",
		"homepageurl": "https://tracktor.bytedge.in",
		"stars": 881
	},
	{
		"owner": "pocketpaw",
		"reponame": "pocketpaw",
		"description": "Your AI agent in 30 seconds. Not 30 hours. Self-hosted, open-source personal AI with desktop installer, multi-agent Command Center(Deep Work), and 7-layer security. Anthropic, OpenAI, or Ollama.",
		"repourl": "https://github.com/pocketpaw/pocketpaw",
		"homepageurl": "http://pocketpaw.xyz/",
		"stars": 616
	},
	{
		"owner": "urania-dev",
		"reponame": "snapp",
		"description": "Yet Another Url Shortner. A simple excercise to learn Svelte.",
		"repourl": "https://github.com/urania-dev/snapp",
		"homepageurl": "https://snapp.li",
		"stars": 390
	},
	{
		"owner": "nickheyer",
		"reponame": "discopanel",
		"description": "A lightweight modded minecraft server hosting suite and management web app.",
		"repourl": "https://github.com/nickheyer/discopanel",
		"homepageurl": "https://discopanel.app",
		"stars": 200
	},
	{
		"owner": "accretional",
		"reponame": "statue",
		"description": "Statue: Svelte + Markdown Static Site Generator, launch a website for your business, blog, portfolio, or product in seconds, with one-line setup",
		"repourl": "https://github.com/accretional/statue",
		"homepageurl": "https://statue.dev",
		"stars": 168
	},
	{
		"owner": "hackclub",
		"reponame": "hackatime",
		"description": "Free, open source, Wakatime-compatible coding time tracker",
		"repourl": "https://github.com/hackclub/hackatime",
		"homepageurl": "https://hackatime.hackclub.com",
		"stars": 114
	},
	{
		"owner": "joachimchauvet",
		"reponame": "modernstack-saas",
		"description": "A modern SaaS template/boilerplate built with SvelteKit, Convex, Better Auth, and shadcn-svelte. Includes subscriptions, auth, user & admin dashboard, user settings, and more.",
		"repourl": "https://github.com/joachimchauvet/modernstack-saas",
		"homepageurl": "https://modernstack-saas.com",
		"stars": 113
	},
	{
		"owner": "chithi-dev",
		"reponame": "chithi",
		"description": "The next generation encrypted file sharing project",
		"repourl": "https://github.com/chithi-dev/chithi",
		"homepageurl": "https://landing.chithi.dev",
		"stars": 101
	}
];

export const otherSites: Dependent[] = [
	{
		"name": "GEO audit",
		"description": "GEO / AI audit that tracks your visibility impact",
		"homepageurl": "https://www.geoaud.it/"
	},
	{
		"name": "RetireNumber",
		"description": "Get a second opinion on your retirement number.",
		"homepageurl": "https://retirenumber.com/"
	},
	{
		"name": "PowerOutage.com",
		"description": "Tracks, records, and aggregates power outage data across the World",
		"homepageurl": "https://poweroutage.com/"
	},
	{
		"name": "IOM UN Migration: Ukraine Regional Response",
		"description": "Needs, Intentions, and Border Crossings",
		"homepageurl": "https://dtm.iom.int/online-interactive-resources/ukraine-regional-response-dashboard/index.html"
	},
	{
		"name": "Loyola Chicago: Center for Criminal Justice",
		"description": "The First Year of the Pretrial Fairness Act",
		"homepageurl": "https://pfa-1yr.loyolaccj.org/"
	},
	{
		"name": "ftop",
		"description": "Comperative performance metrics for Fortnite islands",
		"homepageurl": "https://ftop.app/"
	},
	{
		"name": "Nocturne",
		"description": "A next-generation platform for diabetes management",
		"homepageurl": "https://nocturne.app/"
	},
	{
		"owner": "webstonehq",
		"reponame": "seaquel",
		"description": "A modern, open-source database client for desktop and web.",
		"repourl": "https://github.com/webstonehq/seaquel",
		"homepageurl": "https://seaquel.app",
		"stars": 69
	},
	{
		"owner": "mquandalle",
		"reponame": "mesaidesvelo",
		"description": "Découvrez les aides à l’achat d’un vélo",
		"repourl": "https://github.com/mquandalle/mesaidesvelo",
		"homepageurl": "https://mesaidesvelo.fr",
		"stars": 62
	},
	{
		"owner": "OpenAttribution",
		"reponame": "open-attribution",
		"description": "Open source MMP for ownership of your mobile ad data",
		"repourl": "https://github.com/OpenAttribution/open-attribution",
		"homepageurl": "https://openattribution.dev",
		"stars": 60
	},
	{
		"owner": "Blakintosh",
		"reponame": "svelte-flexiboards",
		"description": "The headless drag-and-drop toolkit for Svelte.",
		"repourl": "https://github.com/Blakintosh/svelte-flexiboards",
		"homepageurl": "https://www.flexiboards.dev",
		"stars": 56
	},
	{
		"owner": "likeon",
		"reponame": "geometa",
		"description": "learnablemeta.com",
		"repourl": "https://github.com/likeon/geometa",
		"homepageurl": "https://learnablemeta.com/",
		"stars": 55
	},
	{
		"owner": "cardano-miners",
		"reponame": "fortuna",
		"description": "All the \"greatness\" of proof of work, now in smart contract form",
		"repourl": "https://github.com/cardano-miners/fortuna",
		"homepageurl": "https://minefortuna.com",
		"stars": 54
	},
	{
		"owner": "appgoblin-dev",
		"reponame": "appgoblin",
		"description": "Free App Store Analytics by AppGoblin. Research Andorid and iOS  SDKs, Ad Networks, Trackers and MMPs. Free ASO marketing tools and app history. ",
		"repourl": "https://github.com/appgoblin-dev/appgoblin",
		"homepageurl": "https://appgoblin.info",
		"stars": 46
	},
	{
		"owner": "industrial-optimization-group",
		"reponame": "DESDEO",
		"description": "An open source fullstack framework for interactive multiobjective optimization and decision-support..",
		"repourl": "https://github.com/industrial-optimization-group/DESDEO",
		"homepageurl": "https://desdeo.readthedocs.io/en/latest/",
		"stars": 44
	},
	{
		"owner": "Michael-Obele",
		"reponame": "Svelte-MiniApps",
		"description": "This project is a collection of small, single-purpose applications written in Svelte 5. Each mini-app tackles a specific task, offering a simple and user-friendly experience for users.",
		"repourl": "https://github.com/Michael-Obele/Svelte-MiniApps",
		"homepageurl": "https://svelte-apps.me/",
		"stars": 42
	},
	{
		"owner": "rivenmedia",
		"reponame": "riven-frontend",
		"description": "Source code for Riven's frontend",
		"repourl": "https://github.com/rivenmedia/riven-frontend",
		"homepageurl": "https://riven.tv",
		"stars": 41
	},
	{
		"owner": "ScholarXIV",
		"reponame": "enkokilish_bench",
		"description": "Amharic Riddle Benchmark for LLMs",
		"repourl": "https://github.com/ScholarXIV/enkokilish_bench",
		"homepageurl": "https://enkokilish-bench.vercel.app",
		"stars": 25
	},
	{
		"owner": "PurelyAnecdotal",
		"reponame": "gradecompass",
		"description": "An advanced grade calculator designed to interface with StudentVUE®.",
		"repourl": "https://github.com/PurelyAnecdotal/gradecompass",
		"homepageurl": "https://gradecompass.org",
		"stars": 18
	},
	{
		"owner": "lipu-linku",
		"reponame": "lipu",
		"description": "lipu Linku, a toki pona dictionary",
		"repourl": "https://github.com/lipu-linku/lipu",
		"homepageurl": "https://linku.la/",
		"stars": 18
	},
	{
		"owner": "thedivtagguy",
		"reponame": "site",
		"description": "Aman's home on the internet",
		"repourl": "https://github.com/thedivtagguy/site",
		"homepageurl": "https://aman.bh",
		"stars": 14
	},
	{
		"owner": "stickerdaniel",
		"reponame": "saas-starter",
		"description": "SaaS starter kit built for humans with agentic workflows. SvelteKit, Convex, BetterAuth and full-stack type safety. Scaffold admin panels and production backends with ease.",
		"repourl": "https://github.com/stickerdaniel/saas-starter",
		"homepageurl": "https://saas.daniel.sticker.name",
		"stars": 14
	},
	{
		"owner": "jpoehnelt",
		"reponame": "blog",
		"description": "Code for my personal website",
		"repourl": "https://github.com/jpoehnelt/blog",
		"homepageurl": "https://justin.poehnelt.com",
		"stars": 13
	},
	{
		"owner": "openstate",
		"reponame": "jodal",
		"description": "Superkrachten voor journalisten. Doorzoek meer dan 2 miljoen overheidsdocumenten op één plek.",
		"repourl": "https://github.com/openstate/jodal",
		"homepageurl": "https://bron.live",
		"stars": 11
	},
	{
		"owner": "imranfadhil",
		"reponame": "quick_pp",
		"description": "Python package for Petrophysical analysis.",
		"repourl": "https://github.com/imranfadhil/quick_pp",
		"homepageurl": "https://quick-pp.readthedocs.io/en/latest/index.html",
		"stars": 10
	}
];
